version: "3.8"

services:
  # Сервис Базы Данных
  db:
    image: ankane/pgvector:v0.5.1 # Postgres 15 + pgvector pre-installed
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432" # Прокидываем на порт 5433 локально, чтобы не конфликтовать с твоим локальным Postgres (если он есть)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Автоматически накатываем schema.sql и миграции при ПЕРВОМ запуске пустой базы
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./migrations/001_enable_vector.sql:/docker-entrypoint-initdb.d/2_vector_migration.sql

  # Сервис Бота
  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # ПЕРЕОПРЕДЕЛЯЕМ хост БД. Внутри докера база доступна по имени сервиса "db"
      - DB_HOST=db
      # Остальные переменные (USER, PASS) возьмутся из .env файла автоматически
    command: python src/bot.py --config config/mipt.json

  # Сервис ML Worker (Пока заглушка, раскомментируем на этапе 3)
  # worker:
  #   build: .
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_HOST=db
  #   command: python src/worker.py

volumes:
  postgres_data:
