CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT NULL;

-- 384 dim = paraphrase-multilingual-MiniLM-L12-v2
ALTER TABLE users
ADD COLUMN IF NOT EXISTS embedding vector(384);
